model:
    arch: enet
data:
    dataset: cityscapes
    train_split: train
    val_split: val
    img_rows: 512
    img_cols: 1024
    path: /projects/amra8468/cityscapes
training:
    train_iters: 300
    batch_size: 10
    val_interval: 10
    n_workers: 5
    print_interval: 10
    optimizer:
        name: 'Adam'
        lr: 5.0e-4
        weight_decay: 2.0e-4
    loss:
        name: 'cross_entropy'
        size_average: False
    lr_schedule: 0.1
    resume: None

