model:
    arch: segnet
data:
    dataset: cityscapes
    train_split: train
    val_split: val
    img_rows: 360
    img_cols: 480
    path: /projects/amra8468/cityscapes
training:
    train_iters: 20
    batch_size: 1
    val_interval: 1
    n_workers: 1
    print_interval: 10
    optimizer:
        name: 'sgd'
        lr: 1.0e-10
        weight_decay: 0.0005
        momentum: 0.99
    loss:
        name: 'cross_entropy'
        size_average: False
    lr_schedule:
    resume: a.pkl
